### PR TITLE
Foundation implementation and framework (missing submanager, idmanager and tests)

### PR DESCRIPTION
**Pull request by jimthematrix**
`internal/conf`: configuration objects for all packages
`internal/errors`: error messages and templates
`internal/fabric`: RPC client and objects that interact with the Fabric nodes via `fabric-sdk-go`
`internal/kafka`: Kafka client via `samara`
`internal/kvstore`: abstract interface for LevelDB based key-value store
`internal/messages`: interfaces and methods for all messages submitted to fabconnect
`internal/rest`: REST server and router
`internal/rest/async`: async request handler and receipt store
`initernal/rest/sync`: sync request handler
`internal/rest/receipt`: receipt store incl. 3 implementations (mongo, leveldb, memory)
`internal/tx`: transaction processor and object
`internal/ws`: websocket server
`cmd`: command definition for launching the REST server

Components that are still missing and to be implemented in a followup PR:
- signing identity management: `internal/identiey`
- event stream management: `internal/eventstream`

### CODE REVIEW

**Comment by nguyer** [comment]
It looks like running `go mod tidy` has trouble so I'm wondering if we need to clean up some dependencies?

```
go mod tidy
go: finding module for package google.golang.org/grpc/examples/helloworld/helloworld
go: finding module for package google.golang.org/grpc/naming
go: found google.golang.org/grpc/examples/helloworld/helloworld in google.golang.org/grpc/examples v0.0.0-20210715165331-ce7bdf50abb1
go: finding module for package google.golang.org/grpc/naming
github.com/hyperledger-labs/firefly-fabconnect/internal/fabric imports
	github.com/hyperledger/fabric-sdk-go/pkg/fabsdk imports
	github.com/hyperledger/fabric-sdk-go/pkg/msp imports
	github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric-ca/sdkinternal/pkg/util imports
	github.com/cloudflare/cfssl/helpers imports
	github.com/google/certificate-transparency-go imports
	go.etcd.io/etcd imports
	go.etcd.io/etcd/etcdmain imports
	go.etcd.io/etcd/proxy/grpcproxy imports
	google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.39.0), but does not contain package google.golang.org/grpc/naming
```

**Comment by defidbpub** [comment]
> It looks like running `go mod tidy` has trouble so I'm wondering if we need to clean up some dependencies?
> 
> ```
> go mod tidy
> go: finding module for package google.golang.org/grpc/examples/helloworld/helloworld
> go: finding module for package google.golang.org/grpc/naming
> go: found google.golang.org/grpc/examples/helloworld/helloworld in google.golang.org/grpc/examples v0.0.0-20210715165331-ce7bdf50abb1
> go: finding module for package google.golang.org/grpc/naming
> github.com/hyperledger-labs/firefly-fabconnect/internal/fabric imports
> 	github.com/hyperledger/fabric-sdk-go/pkg/fabsdk imports
> 	github.com/hyperledger/fabric-sdk-go/pkg/msp imports
> 	github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric-ca/sdkinternal/pkg/util imports
> 	github.com/cloudflare/cfssl/helpers imports
> 	github.com/google/certificate-transparency-go imports
> 	go.etcd.io/etcd imports
> 	go.etcd.io/etcd/etcdmain imports
> 	go.etcd.io/etcd/proxy/grpcproxy imports
> 	google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.39.0), but does not contain package google.golang.org/grpc/naming
> ```

Detail: https://github.com/hyperledger-labs/firefly-fabconnect/issues/10

**Comment by jimthematrix** [comment]
@nguyer thanks for the review, using the pointer by @defidbpub I was able to fix the dependencies issue by rebuilding with `go mod init`

**Comment by jimthematrix** [comment]
had to re-create a new PR #12 from my own fork, in order to be able to push additional commits to address the review comments

**Pull request closed without merging**
